# Generated by Django 3.1.2 on 2020-10-22 18:08

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MavPoints', '0003_auto_20201021_2040'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
